import React from 'react';
import 'jest-styled-components';
import {render, waitFor, act} from 'react-native-testing-library';
import MockedNavigator from '../../__mocks__';
import Home from '../../pages/Home';

import AxiosMock from 'axios-mock-adapter';
import api from '../../services/api';

// @ts-ignore
import {API_KEY} from '@env';

const apiMock = new AxiosMock(api);

describe('Home Page', () => {
  it('Should be able to render Home', async () => {
    apiMock
      .onGet(`movie/upcoming?api_key=${API_KEY}&language=en-US&page=1`)
      .reply(200, {
        results: [
          {
            popularity: 520.507,
            vote_count: 131,
            video: false,
            poster_path: '/A3z0KMLIEGL22mVrgaV7KDxKRmT.jpg',
            id: 539885,
            adult: false,
            backdrop_path: '/ekkuqt9Q2ad1F7xq2ZONP0oq36P.jpg',
            original_language: 'en',
            original_title: 'Ava',
            genre_ids: [28, 80, 18, 53],
            title: 'Ava',
            vote_average: 6.3,
            overview:
              'A black ops assassin is forced to fight for her own survival after a job goes dangerously wrong.',
            release_date: '2020-08-06',
          },
          {
            popularity: 342.698,
            vote_count: 533,
            video: false,
            poster_path: '/k68nPLbIST6NP96JmTxmZijEvCA.jpg',
            id: 577922,
            adult: false,
            backdrop_path: '/wzJRB4MKi3yK138bJyuL9nx47y6.jpg',
            original_language: 'en',
            original_title: 'Tenet',
            genre_ids: [28, 53],
            title: 'Tenet',
            vote_average: 7.6,
            overview:
              'Armed with only one word - Tenet - and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.',
            release_date: '2020-08-22',
          },
          {
            popularity: 161.117,
            vote_count: 48,
            video: false,
            poster_path: '/xZNw9xxtwbEf25NYoz52KdbXHPM.jpg',
            id: 340102,
            adult: false,
            backdrop_path: '/2AFZyra0Ddwl2oBDhClvD1qSIL6.jpg',
            original_language: 'en',
            original_title: 'The New Mutants',
            genre_ids: [28, 12, 27, 878],
            title: 'The New Mutants',
            vote_average: 5.5,
            overview:
              'Five young mutants, just discovering their abilities while held in a secret facility against their will, fight to escape their past sins and save themselves.',
            release_date: '2020-08-26',
          },
          {
            popularity: 116.767,
            vote_count: 36,
            video: false,
            poster_path: '/4V2nTPfeB59TcqJcUfQ9ziTi7VN.jpg',
            id: 501979,
            adult: false,
            backdrop_path: '/oazPqs1z78LcIOFslbKtJLGlueo.jpg',
            original_language: 'en',
            original_title: 'Bill & Ted Face the Music',
            genre_ids: [12, 35, 878],
            title: 'Bill & Ted Face the Music',
            vote_average: 6.2,
            overview:
              'Yet to fulfill their rock and roll destiny, the now middle-aged best friends Bill and Ted set out on a new adventure when a visitor from the future warns them that only their song can save life as we know it. Along the way, they are helped by their daughters, a new batch of historical figures and a few music legends—to seek the song that will set their world right and bring harmony to the universe.',
            release_date: '2020-08-27',
          },
          {
            popularity: 122.871,
            vote_count: 309,
            video: false,
            poster_path: '/hPkqY2EMqWUnFEoedukilIUieVG.jpg',
            id: 531876,
            adult: false,
            backdrop_path: '/n1RohH2VoK1CdVI2fXvcP19dSlm.jpg',
            original_language: 'en',
            original_title: 'The Outpost',
            genre_ids: [28, 18, 36, 10752],
            title: 'The Outpost',
            vote_average: 6.7,
            overview:
              'A small unit of U.S. soldiers, alone at the remote Combat Outpost Keating, located deep in the valley of three mountains in Afghanistan, battles to defend against an overwhelming force of Taliban fighters in a coordinated attack. The Battle of Kamdesh, as it was known, was the bloodiest American engagement of the Afghan War in 2009 and Bravo Troop 3-61 CAV became one of the most decorated units of the 19-year conflict.',
            release_date: '2020-06-24',
          },
          {
            popularity: 108.389,
            vote_count: 1070,
            video: false,
            poster_path: '/7W0G3YECgDAfnuiHG91r8WqgIOe.jpg',
            id: 446893,
            adult: false,
            backdrop_path: '/qsxhnirlp7y4Ae9bd11oYJSX59j.jpg',
            original_language: 'en',
            original_title: 'Trolls World Tour',
            genre_ids: [12, 16, 35, 14, 10402, 10751],
            title: 'Trolls World Tour',
            vote_average: 7.6,
            overview:
              'Queen Poppy and Branch make a surprising discovery — there are other Troll worlds beyond their own, and their distinct differences create big clashes between these various tribes. When a mysterious threat puts all of the Trolls across the land in danger, Poppy, Branch, and their band of friends must embark on an epic quest to create harmony among the feuding Trolls to unite them against certain doom.',
            release_date: '2020-03-12',
          },
          {
            popularity: 87.366,
            vote_count: 1,
            video: false,
            poster_path: '/aKx1ARwG55zZ0GpRvU2WrGrCG9o.jpg',
            id: 337401,
            adult: false,
            backdrop_path: '/xl5oCFLVMo4d4Pgxvrf8Jmc2IlA.jpg',
            original_language: 'en',
            original_title: 'Mulan',
            genre_ids: [28, 18, 14, 10752],
            title: 'Mulan',
            vote_average: 2,
            overview:
              'When the Emperor of China issues a decree that one man per family must serve in the Imperial Chinese Army to defend the country from Huns, Hua Mulan, the eldest daughter of an honored warrior, steps in to take the place of her ailing father. She is spirited, determined and quick on her feet. Disguised as a man by the name of Hua Jun, she is tested every step of the way and must harness her innermost strength and embrace her true potential.',
            release_date: '2020-09-04',
          },
          {
            popularity: 81.299,
            vote_count: 99,
            video: false,
            poster_path: '/zQFjMmE3K9AX5QrBL1SXIxYQ9jz.jpg',
            id: 579583,
            adult: false,
            backdrop_path: '/5rwcd24GGltKiqdPT4G2dmchLr9.jpg',
            original_language: 'en',
            original_title: 'The King of Staten Island',
            genre_ids: [35, 18],
            title: 'The King of Staten Island',
            vote_average: 6.7,
            overview:
              'Scott has been a case of arrested development ever since his firefighter father died when he was seven. He’s now reached his mid-20s having achieved little, chasing a dream of becoming a tattoo artist that seems far out of reach. As his ambitious younger sister heads off to college, Scott is still living with his exhausted ER nurse mother and spends his days smoking weed, hanging with the guys — Oscar, Igor and Richie — and secretly hooking up with his childhood friend Kelsey. But when his mother starts dating a loudmouth firefighter named Ray, it sets off a chain of events that will force Scott to grapple with his grief and take his first tentative steps toward moving forward in life.',
            release_date: '2020-07-22',
          },
          {
            popularity: 75.385,
            vote_count: 465,
            video: false,
            poster_path: '/yf5IuMW6GHghu39kxA0oFx7Bxmj.jpg',
            id: 587792,
            adult: false,
            backdrop_path: '/d7JUXVvjvVCXWs1mlpyO5ESdWdT.jpg',
            original_language: 'en',
            original_title: 'Palm Springs',
            genre_ids: [35, 14, 9648, 10749],
            title: 'Palm Springs',
            vote_average: 7.6,
            overview:
              'When carefree Nyles and reluctant maid of honor Sarah have a chance encounter at a Palm Springs wedding, things get complicated when they find themselves unable to escape the venue, themselves, or each other.',
            release_date: '2020-07-10',
          },
          {
            popularity: 75.581,
            vote_count: 7,
            video: false,
            poster_path: '/ijcykNO87JLCgxUltTFqHwlK2yT.jpg',
            id: 613504,
            adult: false,
            backdrop_path: '/dZJJDmiwp0W1NE74SY5WV00v0Ec.jpg',
            original_language: 'en',
            original_title: 'After We Collided',
            genre_ids: [18, 10749],
            title: 'After We Collided',
            vote_average: 6.2,
            overview:
              'Tessa finds herself struggling with her complicated relationship with Hardin; she faces a dilemma that could change their lives forever.',
            release_date: '2020-09-02',
          },
          {
            popularity: 68.37,
            vote_count: 1308,
            video: false,
            poster_path: '/wxPhn4ef1EAo5njxwBkAEVrlJJG.jpg',
            id: 514847,
            adult: false,
            backdrop_path: '/qfQ78ZKiouoM2yhAnfNblp9ijQE.jpg',
            original_language: 'en',
            original_title: 'The Hunt',
            genre_ids: [28, 27, 53],
            title: 'The Hunt',
            vote_average: 6.6,
            overview:
              "Twelve strangers wake up in a clearing. They don't know where they are—or how they got there. In the shadow of a dark internet conspiracy theory, ruthless elitists gather at a remote location to hunt humans for sport. But their master plan is about to be derailed when one of the hunted turns the tables on her pursuers.",
            release_date: '2020-03-11',
          },
          {
            popularity: 77.916,
            vote_count: 646,
            video: false,
            poster_path: '/4w1ItwCJCTtSi9nPfJC1vU6NIVg.jpg',
            id: 413518,
            adult: false,
            backdrop_path: '/AdqOBPw4PdtzOcfEuQuZ8MNeTKb.jpg',
            original_language: 'it',
            original_title: 'Pinocchio',
            genre_ids: [12, 18, 14, 10751],
            title: 'Pinocchio',
            vote_average: 6.9,
            overview:
              'In this live-action adaptation of the beloved fairytale, old woodcarver Geppetto fashions a wooden puppet, Pinocchio, who magically comes to life. Pinocchio longs for adventure and is easily led astray, encountering magical beasts, fantastical spectacles, while making friends and foes along his journey. However, his dream is to become a real boy, which can only come true if he finally changes his ways.',
            release_date: '2019-12-19',
          },
          {
            popularity: 46.81,
            vote_count: 79,
            video: false,
            poster_path: '/7I8BmtqjLyyMf3EjrUEIQs0gFYw.jpg',
            id: 625568,
            adult: false,
            backdrop_path: '/e7bpDu3RKsjOYLSt9gHYT2c32Zd.jpg',
            original_language: 'en',
            original_title: 'Unhinged',
            genre_ids: [28, 53],
            title: 'Unhinged',
            vote_average: 6.2,
            overview:
              'A case of road rage turns into full-blown terror when an unstable driver follows a woman and her son.',
            release_date: '2020-07-02',
          },
          {
            popularity: 43.922,
            vote_count: 591,
            video: false,
            poster_path: '/myf3qzpeN0JbuFRPwSpJcz7rmAT.jpg',
            id: 458305,
            adult: false,
            backdrop_path: '/jZ4YdDCnfK4cO13do9J4JaT8d2O.jpg',
            original_language: 'en',
            original_title: 'Vivarium',
            genre_ids: [27, 878, 53],
            title: 'Vivarium',
            vote_average: 5.9,
            overview:
              'A young woman and her fiancé are in search of the perfect starter home. After following a mysterious real estate agent to a new housing development, the couple finds themselves trapped in a maze of identical houses and forced to raise an otherworldly child.',
            release_date: '2019-09-07',
          },
          {
            popularity: 33.237,
            vote_count: 344,
            video: false,
            poster_path: '/zGVbrulkupqpbwgiNedkJPyQum4.jpg',
            id: 592350,
            adult: false,
            backdrop_path: '/9guoVF7zayiiUq5ulKQpt375VIy.jpg',
            original_language: 'ja',
            original_title:
              '僕のヒーローアカデミア THE MOVIE ヒーローズ：ライジング',
            genre_ids: [28, 16],
            title: 'My Hero Academi: Heroes Rising',
            vote_average: 8.7,
            overview:
              "Class 1-A visits Nabu Island where they finally get to do some real hero work. The place is so peaceful that it's more like a vacation … until they're attacked by a villain with an unfathomable Quirk! His power is eerily familiar, and it looks like Shigaraki had a hand in the plan. But with All Might retired and citizens' lives on the line, there's no time for questions. Deku and his friends are the next generation of heroes, and they're the island's only hope.",
            release_date: '2019-12-20',
          },
          {
            popularity: 48.896,
            vote_count: 20,
            video: false,
            poster_path: '/cDbOrc2RtIA37nLm0CzVpFLrdaG.jpg',
            id: 513584,
            adult: false,
            backdrop_path: '/qEo36RiT8w4hMFlf9KohOSuX3HZ.jpg',
            original_language: 'en',
            original_title: 'Think Like a Dog',
            genre_ids: [35, 18, 10751],
            title: 'Think Like a Dog',
            vote_average: 6.3,
            overview:
              'A 12-year-old tech prodigy whose science experiment goes awry and he forges a telepathic connection with his best friend, his dog. The duo join forces and use their unique perspectives on life to comically overcome complications of family and school.',
            release_date: '2020-08-06',
          },
          {
            popularity: 36.727,
            vote_count: 164,
            video: false,
            poster_path: '/akHIQu8W3rOgT28r25ggXaKcQIr.jpg',
            id: 480857,
            adult: false,
            backdrop_path: '/e7tjpKP36Xd6BzyTMZo4AUe86VM.jpg',
            original_language: 'en',
            original_title: 'Radioactive',
            genre_ids: [18, 36, 10749],
            title: 'Radioactive',
            vote_average: 6.3,
            overview:
              'Tells the story of Nobel Prize winner Marie Curie and her extraordinary scientific discoveries — through the prism of her marriage to husband Pierre — and the seismic and transformative effects their discovery of radium had on the 20th century.',
            release_date: '2020-03-11',
          },
          {
            popularity: 46.299,
            vote_count: 59,
            video: false,
            poster_path: '/yVsINl4Aa9vvQ9lE2LF77qNj7AP.jpg',
            id: 617708,
            adult: false,
            backdrop_path: '/oj9pEWQq5higRzKWiE8f0d5hBSb.jpg',
            original_language: 'es',
            original_title: 'La Llorona',
            genre_ids: [18, 27, 53],
            title: 'La Llorona',
            vote_average: 5.9,
            overview:
              'A tale of horror and fantasy, ripe with suspense, and an urgent metaphor of Guatemalan recent history and its unhealed political wounds.',
            release_date: '2020-01-22',
          },
          {
            popularity: 38.611,
            vote_count: 126,
            video: false,
            poster_path: '/jOY3dDCzjygXzumYeJ9UIyETzuj.jpg',
            id: 550738,
            adult: false,
            backdrop_path: '/tV15mHVJkFXlJ0P8AM7cckuuo6i.jpg',
            original_language: 'fr',
            original_title: 'Spycies',
            genre_ids: [28, 12, 16, 35, 10751],
            title: 'Spycies',
            vote_average: 8.1,
            overview:
              'Vladimir and Hector, two secret agents opposed in every way, are trying to recover a top secret material stolen by unknown intruders.',
            release_date: '2020-01-11',
          },
          {
            popularity: 32.008,
            vote_count: 0,
            video: false,
            poster_path: '/jt0GipCbR6QwrhqlL6n5nTbC51y.jpg',
            id: 531033,
            adult: false,
            backdrop_path: '/myVuL1xUYzsFV3gOjX5ecucHpwq.jpg',
            original_language: 'en',
            original_title: 'I Am Woman',
            genre_ids: [18, 10402],
            title: 'I Am Woman',
            vote_average: 0,
            overview:
              'The story of Helen Reddy, who, in 1966, landed in New York with her three-year-old daughter, a suitcase, and $230 in her pocket. Within weeks, she was broke. Within months, she was in love. Within five years, she was one of the biggest superstars of her time and an icon of the 1970s feminist movement who wrote a song which galvanized a generation of women to fight for change.',
            release_date: '2020-09-11',
          },
        ],
        page: 1,
        total_results: 183,
        dates: {
          maximum: '2020-09-20',
          minimum: '2020-09-05',
        },
        total_pages: 10,
      });

    apiMock.onGet(`configuration?api_key=${API_KEY}`).reply(200, {
      images: {
        base_url: 'http://image.tmdb.org/t/p/',
        secure_base_url: 'https://image.tmdb.org/t/p/',
        backdrop_sizes: ['w300', 'w780', 'w1280', 'original'],
        logo_sizes: ['w45', 'w92', 'w154', 'w185', 'w300', 'w500', 'original'],
        poster_sizes: [
          'w92',
          'w154',
          'w185',
          'w342',
          'w500',
          'w780',
          'original',
        ],
        profile_sizes: ['w45', 'w185', 'h632', 'original'],
        still_sizes: ['w92', 'w185', 'w300', 'original'],
      },
      change_keys: [
        'adult',
        'air_date',
        'also_known_as',
        'alternative_titles',
        'biography',
        'birthday',
        'budget',
        'cast',
        'certifications',
        'character_names',
        'created_by',
        'crew',
        'deathday',
        'episode',
        'episode_number',
        'episode_run_time',
        'freebase_id',
        'freebase_mid',
        'general',
        'genres',
        'guest_stars',
        'homepage',
        'images',
        'imdb_id',
        'languages',
        'name',
        'network',
        'origin_country',
        'original_name',
        'original_title',
        'overview',
        'parts',
        'place_of_birth',
        'plot_keywords',
        'production_code',
        'production_companies',
        'production_countries',
        'releases',
        'revenue',
        'runtime',
        'season',
        'season_number',
        'season_regular',
        'spoken_languages',
        'status',
        'tagline',
        'title',
        'translations',
        'tvdb_id',
        'tvrage_id',
        'type',
        'video',
        'videos',
      ],
    });
    render(<MockedNavigator component={Home} />);
  });
});
